<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        // First, get a user ID to associate with the jobs
        $userId = DB::table('users')->first()->id;

        $jobs = [
            [
                'title' => 'Senior Software Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '100000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for an experienced software engineer to join our growing team.',
                'benefits' => 'Health insurance, Yearly bonus, Flexible working hours',
                'responsibility' => 'Develop and maintain web applications, Lead technical projects',
                'qualifications' => 'BSc in CSE or related field, 5+ years experience',
                'keywords' => 'PHP, Laravel, MySQL, JavaScript',
                'experience' => '5-7 years',
                'company_name' => 'Tech Solutions BD',
                'company_location' => 'Gulshan-2, Dhaka',
                'company_website' => 'https://techsolutionsbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Digital Marketing Manager',
                'category_id' => 2,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '60000',
                'location' => 'Banani, Dhaka',
                'description' => 'Seeking a creative digital marketing manager to lead our online presence.',
                'benefits' => 'Performance bonus, Training opportunities',
                'responsibility' => 'Manage social media, SEO, and content marketing',
                'qualifications' => 'Bachelor\'s degree in Marketing, 3+ years experience',
                'keywords' => 'Digital Marketing, SEO, Social Media',
                'experience' => '3-5 years',
                'company_name' => 'Digital Wave BD',
                'company_location' => 'Banani, Dhaka',
                'company_website' => 'https://digitalwavebd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'UI/UX Designer',
                'category_id' => 3,
                'job_type_id' => 2,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '50000',
                'location' => 'Mirpur, Dhaka',
                'description' => 'Join our creative team as a UI/UX designer.',
                'benefits' => 'Remote work options, Creative freedom',
                'responsibility' => 'Design user interfaces and experiences',
                'qualifications' => 'Bachelor\'s in Design, 2+ years experience',
                'keywords' => 'UI/UX, Figma, Adobe XD',
                'experience' => '2-4 years',
                'company_name' => 'Creative Minds BD',
                'company_location' => 'Mirpur-10, Dhaka',
                'company_website' => 'https://creativemindsbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Mobile App Developer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 3,
                'salary' => '85000',
                'location' => 'Uttara, Dhaka',
                'description' => 'Looking for skilled mobile app developers.',
                'benefits' => 'Health insurance, Performance bonus',
                'responsibility' => 'Develop and maintain mobile applications',
                'qualifications' => 'BSc in CSE, 3+ years experience',
                'keywords' => 'React Native, Flutter, iOS, Android',
                'experience' => '3-5 years',
                'company_name' => 'MobileTech BD',
                'company_location' => 'Uttara, Dhaka',
                'company_website' => 'https://mobiletechbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Content Writer',
                'category_id' => 4,
                'job_type_id' => 2,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '50000',
                'location' => 'Dhanmondi, Dhaka',
                'description' => 'Seeking creative content writers for our digital platform.',
                'benefits' => 'Flexible hours, Remote work options',
                'responsibility' => 'Create engaging content for various platforms',
                'qualifications' => 'Bachelor\'s in English/Journalism',
                'keywords' => 'Content Writing, SEO, Blogging',
                'experience' => '1-3 years',
                'company_name' => 'Content Hub BD',
                'company_location' => 'Dhanmondi, Dhaka',
                'company_website' => 'https://contenthubbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'DevOps Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '110000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for an experienced DevOps engineer to manage our infrastructure.',
                'benefits' => 'Health insurance, Yearly bonus, Remote work options',
                'responsibility' => 'Manage cloud infrastructure, CI/CD pipelines',
                'qualifications' => 'BSc in CSE, 4+ years experience',
                'keywords' => 'AWS, Docker, Kubernetes, Jenkins',
                'experience' => '4-6 years',
                'company_name' => 'CloudTech BD',
                'company_location' => 'Gulshan-1, Dhaka',
                'company_website' => 'https://cloudtechbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Scientist',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '100000',
                'location' => 'Banani, Dhaka',
                'description' => 'Seeking a data scientist to analyze and interpret complex data sets.',
                'benefits' => 'Health insurance, Performance bonus, Training opportunities',
                'responsibility' => 'Develop machine learning models, Data analysis',
                'qualifications' => 'MSc in Data Science/Statistics, 3+ years experience',
                'keywords' => 'Python, R, Machine Learning, SQL',
                'experience' => '3-5 years',
                'company_name' => 'Data Insights BD',
                'company_location' => 'Banani, Dhaka',
                'company_website' => 'https://datainsightsbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Product Manager',
                'category_id' => 2,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '120000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for a product manager to drive product development.',
                'benefits' => 'Health insurance, Yearly bonus, Stock options',
                'responsibility' => 'Product strategy, Roadmap planning',
                'qualifications' => 'MBA, 5+ years experience',
                'keywords' => 'Product Management, Agile, JIRA',
                'experience' => '5-7 years',
                'company_name' => 'ProductPro BD',
                'company_location' => 'Gulshan-2, Dhaka',
                'company_website' => 'https://productprobd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Frontend Developer',
                'category_id' => 1,
                'job_type_id' => 2,
                'user_id' => $userId,
                'vacancy' => 3,
                'salary' => '75000',
                'location' => 'Mirpur, Dhaka',
                'description' => 'Seeking frontend developers to build modern web applications.',
                'benefits' => 'Health insurance, Flexible hours',
                'responsibility' => 'Develop responsive web interfaces',
                'qualifications' => 'BSc in CSE, 2+ years experience',
                'keywords' => 'React, Vue.js, JavaScript, CSS',
                'experience' => '2-4 years',
                'company_name' => 'WebTech BD',
                'company_location' => 'Mirpur-10, Dhaka',
                'company_website' => 'https://webtechbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Backend Developer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '85000',
                'location' => 'Uttara, Dhaka',
                'description' => 'Looking for backend developers to build scalable applications.',
                'benefits' => 'Health insurance, Performance bonus',
                'responsibility' => 'Develop and maintain backend services',
                'qualifications' => 'BSc in CSE, 3+ years experience',
                'keywords' => 'Node.js, Python, Django, PostgreSQL',
                'experience' => '3-5 years',
                'company_name' => 'BackendPro BD',
                'company_location' => 'Uttara, Dhaka',
                'company_website' => 'https://backendprobd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'QA Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '65000',
                'location' => 'Dhanmondi, Dhaka',
                'description' => 'Seeking QA engineers to ensure software quality.',
                'benefits' => 'Health insurance, Training opportunities',
                'responsibility' => 'Test planning, Automation testing',
                'qualifications' => 'BSc in CSE, 2+ years experience',
                'keywords' => 'Selenium, JUnit, TestNG, API Testing',
                'experience' => '2-4 years',
                'company_name' => 'QualityTech BD',
                'company_location' => 'Dhanmondi, Dhaka',
                'company_website' => 'https://qualitytechbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'System Administrator',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '80000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for a system administrator to manage IT infrastructure.',
                'benefits' => 'Health insurance, Yearly bonus',
                'responsibility' => 'System maintenance, Security management',
                'qualifications' => 'BSc in CSE, 4+ years experience',
                'keywords' => 'Linux, Windows Server, Networking',
                'experience' => '4-6 years',
                'company_name' => 'SysAdmin BD',
                'company_location' => 'Gulshan-1, Dhaka',
                'company_website' => 'https://sysadminbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Business Analyst',
                'category_id' => 2,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '70000',
                'location' => 'Banani, Dhaka',
                'description' => 'Seeking business analysts to bridge business and technology.',
                'benefits' => 'Health insurance, Performance bonus',
                'responsibility' => 'Requirements gathering, Process analysis',
                'qualifications' => 'MBA, 3+ years experience',
                'keywords' => 'Business Analysis, SQL, UML',
                'experience' => '3-5 years',
                'company_name' => 'BusinessPro BD',
                'company_location' => 'Banani, Dhaka',
                'company_website' => 'https://businessprobd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '85000',
                'location' => 'Uttara, Dhaka',
                'description' => 'Looking for network engineers to manage network infrastructure.',
                'benefits' => 'Health insurance, Yearly bonus',
                'responsibility' => 'Network design, Security implementation',
                'qualifications' => 'BSc in CSE, 4+ years experience',
                'keywords' => 'Cisco, Juniper, Network Security',
                'experience' => '4-6 years',
                'company_name' => 'NetworkPro BD',
                'company_location' => 'Uttara, Dhaka',
                'company_website' => 'https://networkprobd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Technical Writer',
                'category_id' => 4,
                'job_type_id' => 2,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '55000',
                'location' => 'Dhanmondi, Dhaka',
                'description' => 'Seeking technical writers to create documentation.',
                'benefits' => 'Flexible hours, Remote work options',
                'responsibility' => 'Create technical documentation',
                'qualifications' => 'Bachelor\'s in English/Technical Writing',
                'keywords' => 'Technical Writing, Documentation',
                'experience' => '2-4 years',
                'company_name' => 'TechDocs BD',
                'company_location' => 'Dhanmondi, Dhaka',
                'company_website' => 'https://techdocsbd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Security Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '100000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for security engineers to protect our systems.',
                'benefits' => 'Health insurance, Yearly bonus',
                'responsibility' => 'Security implementation, Vulnerability assessment',
                'qualifications' => 'BSc in CSE, 4+ years experience',
                'keywords' => 'Security, Penetration Testing, CISSP',
                'experience' => '4-6 years',
                'company_name' => 'SecureTech BD',
                'company_location' => 'Gulshan-2, Dhaka',
                'company_website' => 'https://securetechbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Database Administrator',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '110000',
                'location' => 'Banani, Dhaka',
                'description' => 'Seeking database administrators to manage our databases.',
                'benefits' => 'Health insurance, Performance bonus',
                'responsibility' => 'Database management, Performance tuning',
                'qualifications' => 'BSc in CSE, 4+ years experience',
                'keywords' => 'MySQL, PostgreSQL, Oracle',
                'experience' => '4-6 years',
                'company_name' => 'DataBasePro BD',
                'company_location' => 'Banani, Dhaka',
                'company_website' => 'https://databaseprobd.com',
                'status' => 1,
                'isFeatured' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cloud Architect',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '125000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for cloud architects to design cloud solutions.',
                'benefits' => 'Health insurance, Yearly bonus, Stock options',
                'responsibility' => 'Cloud architecture design, Migration planning',
                'qualifications' => 'BSc in CSE, 6+ years experience',
                'keywords' => 'AWS, Azure, GCP, Cloud Architecture',
                'experience' => '6-8 years',
                'company_name' => 'CloudArch BD',
                'company_location' => 'Gulshan-1, Dhaka',
                'company_website' => 'https://cloudarchbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'AI Engineer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 2,
                'salary' => '115000',
                'location' => 'Uttara, Dhaka',
                'description' => 'Seeking AI engineers to develop machine learning solutions.',
                'benefits' => 'Health insurance, Performance bonus, Research opportunities',
                'responsibility' => 'AI model development, Research',
                'qualifications' => 'MSc in AI/ML, 3+ years experience',
                'keywords' => 'Machine Learning, Deep Learning, Python',
                'experience' => '3-5 years',
                'company_name' => 'AI Solutions BD',
                'company_location' => 'Uttara, Dhaka',
                'company_website' => 'https://aisolutionsbd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Blockchain Developer',
                'category_id' => 1,
                'job_type_id' => 1,
                'user_id' => $userId,
                'vacancy' => 1,
                'salary' => '120000',
                'location' => 'Gulshan, Dhaka',
                'description' => 'Looking for blockchain developers to build decentralized applications.',
                'benefits' => 'Health insurance, Yearly bonus, Remote work options',
                'responsibility' => 'Smart contract development, DApp development',
                'qualifications' => 'BSc in CSE, 3+ years experience',
                'keywords' => 'Solidity, Ethereum, Web3.js',
                'experience' => '3-5 years',
                'company_name' => 'BlockChainPro BD',
                'company_location' => 'Gulshan-2, Dhaka',
                'company_website' => 'https://blockchainprobd.com',
                'status' => 1,
                'isFeatured' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('jobs')->insert($jobs);
    }
} 